name: Build and Push Docker Image

on:
  merge_group:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  PUBLIC_REGISTRY: us-docker.pkg.dev/pvn-infra/pvn-public
  VERSION: '0.6.1'

jobs:
  build-prod-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/868387978158/locations/global/workloadIdentityPools/pvn-infra/providers/github"
          service_account: "public-docker-write@pvn-infra.iam.gserviceaccount.com"
          token_format: "access_token"
          create_credentials_file: true
      - uses: "docker/login-action@v1"
        with:
          registry: "us-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64/v8,linux/amd64
          push: true
          context: .
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ env.PUBLIC_REGISTRY }}/pvnctl:latest
            ${{ env.PUBLIC_REGISTRY }}/pvnctl:${{ env.VERSION }}
